[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="locale" type="java.util.Locale" --]
[#-- @ftlvariable name="personality" type="billiongoods.core.Personality" --]
[#-- @ftlvariable name="messageSource" type="billiongoods.core.MessageFormatter" --]