SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL';

CREATE TABLE IF NOT EXISTS `billiongoods`.`account_role` (
  `pid`  BIGINT(20)  NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pid`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_general_ci;

ALTER TABLE `billiongoods`.`account_personality` CHANGE COLUMN `nickname` `username` VARCHAR(100)
CHARACTER SET 'utf8'
COLLATE 'utf8_general_ci' NOT NULL
, DROP INDEX `username_UNIQUE`;

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
