ALTER TABLE `billiongoods`.`store_article_relationship`
CHANGE COLUMN `groupId` `groupId` INT(11) NULL DEFAULT NULL
AFTER `articleId`,
CHANGE COLUMN `articleId` `articleId` INT(11) NULL DEFAULT NULL,
CHANGE COLUMN `type` `type` SMALLINT(6) NULL DEFAULT NULL,
ADD COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT
FIRST,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`id`);